config/routes.rb
Rails.application.routes.draw do
  resources :info_pages
  resources :dogs
  root 'welcome#index'

  get 'welcome' => 'welcome#index'
  get 'about' => 'welcome#about'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/info_page.rb
class InfoPage < ActiveRecord::Base

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :age, :description, :avatar)
    end
end

app/controllers/info_pages_controller.rb
class InfoPagesController < ApplicationController
  before_action :set_info_page, only: [:show, :edit, :update, :destroy]

  # GET /info_pages
  # GET /info_pages.json
  def index
    @info_pages = InfoPage.all
  end

  # GET /info_pages/1
  # GET /info_pages/1.json
  def show
  end

  # GET /info_pages/new
  def new
    @info_page = InfoPage.new
  end

  # GET /info_pages/1/edit
  def edit
  end

  # POST /info_pages
  # POST /info_pages.json
  def create
    @info_page = InfoPage.new(info_page_params)

    respond_to do |format|
      if @info_page.save
        format.html { redirect_to @info_page, notice: 'Info page was successfully created.' }
        format.json { render :show, status: :created, location: @info_page }
      else
        format.html { render :new }
        format.json { render json: @info_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_pages/1
  # PATCH/PUT /info_pages/1.json
  def update
    respond_to do |format|
      if @info_page.update(info_page_params)
        format.html { redirect_to @info_page, notice: 'Info page was successfully updated.' }
        format.json { render :show, status: :ok, location: @info_page }
      else
        format.html { render :edit }
        format.json { render json: @info_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_pages/1
  # DELETE /info_pages/1.json
  def destroy
    @info_page.destroy
    respond_to do |format|
      format.html { redirect_to info_pages_url, notice: 'Info page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info_page
      @info_page = InfoPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_page_params
      params.require(:info_page).permit(:information)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/info_pages_helper.rb
module InfoPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="navbar navbar-default">
  <div class="navbar-inner">
  <div class="container">
    <a class="navbar-brand" href="#"><strong>RESCUE ME</strong></a>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", welcome_path %></li>
      <li><a href="#">About Us</a></li>
      <li class="divider-vertical"></li>
      <li class="active"><a href="dogs#index">Adopt</a></li>
      <li><a href="info_pages#index">Information</a></li>
      <li><a href="#">Sponsor</a></li>
    </ul>
  </div>
</div>

<h1>Dogs that need Forever Homes</h1>

  <div class="row">
    <% @dogs.each do |dog| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
           <%= image_tag dog.avatar.url(:medium), class: "img-responsive" %>
           <h2><%= dog.name %></h2>
           <h3>Dog Age Group: <%= dog.age %></h3>
           <p>Description: <%= dog.description %></p>

           <div class="btn-group">
            <%= link_to 'Show', dog, class:"btn btn-primary" %>
            <%= link_to 'Edit', edit_dog_path(dog),  class:"btn btn-warning" %>
            <%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' },  class:"btn btn-danger"%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Dog', new_dog_path, class: "btn btn-info" %>


<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2 style="text-align: center;"><a href="about.html.erb"><img class=" wp-image-540" title="Adoptable Dogs" src="http://therescueddog.org/wp-content/uploads/2014/02/audrey.png" alt="dog" width="183" height="184"></a></h2>
        <h2 style="text-align: center;"><a title="">Adoptable Dogs</a></h2>
        <p style="text-align: justify;">Check out our list of available Rescued Dogs. All of our dogs have been examined by a vet, spayed or neutered, vaccinated, and microchipped.  Interested in one of our dogs? Fill out an <a title="Adoption Application" href="about.html.erb">Adoption Application</a>, and when approved we will then setup a time to meet our Rescued Dogs!</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2 style="text-align: center;"><a href="http://therescueddog.org/mutt-match/"><img class="size-full wp-image-559" title="Mutt Match" src="http://therescueddog.org/wp-content/uploads/2013/09/thor_button.png" alt="thor_button" width="183" height="184"></a></h2>
        <h2 style="text-align: center;"><a title="Dog Match" href="http://therescueddog.org/mutt-match/">Dog Match</a></h2>
        <p style="text-align: justify;">Having a hard time finding the right dog for your family and still interested in rescuing? Check out our Dog Match program! This innovated program helps families find their perfect dog. We search shelters for your perfect match (breed, temperament, age, energy level). Once we find a good match for your family, the dog will be vetted and behaviorally evaluated to ensure a good match is made.</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h2 style="text-align: center;"><a href="http://therescueddog.org/sponsor-a-rescue-dog/"><img class="alignnone wp-image-563" title="Sponsor a Dog" src="http://therescueddog.org/wp-content/uploads/2013/09/floyd_button.png" alt="floyd_button" width="187" height="188"></a></h2>
        <h2 style="text-align: center;"><a title="Why Foster?" href="http://therescueddog.org/sponsor-a-rescue-dog/">Sponsor a Dog</a></h2>
        <p style="text-align: justify;">Want to help us out, sponsoring a dog is the next best thing! By sponsoring a dog, spay or neuter, food, or vaccinations, you are helping us save another dog in need. We could not continue to rescue without your generosity. Our Rescued Dogs thank you!</p>
      </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="navbar navbar-default">
  <div class="navbar-inner">
  <div class="container">
    <a class="navbar-brand" href="#"><strong>RESCUE ME</strong></a>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", welcome_path %></li>
      <li><a href="#">About Us</a></li>
      <li class="divider-vertical"></li>
      <li class="active"><a href="dogs#show">Adopt</a></li>
      <li><a href="info_pages#index">Information</a></li>
      <li><a href="#">Sponsor</a></li>
    </ul>
  </div>
</div>




<h1><%= @dog.name %></h1>
<h2><%= @dog.age %></h2>

<%= image_tag @dog.avatar.url, width: '100', height: '100' %>
<p><strong>Description: </strong><%= @dog.description[0..20]%> ...</p>


<div class="btn-group">
  <%= link_to 'Edit', edit_dog_path(@dog), class: "btn btn-default" %>
  <%= link_to 'Back', dogs_path, class: "btn btn-default" %>
</div>

app/views/info_pages/_form.html.erb
<%= form_for(@info_page) do |f| %>
  <% if @info_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info_page.errors.count, "error") %> prohibited this info_page from being saved:</h2>

      <ul>
      <% @info_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :information %><br>
    <%= f.text_field :information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/info_pages/edit.html.erb
<h1>Editing Info Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @info_page %> |
<%= link_to 'Back', info_pages_path %>

app/views/info_pages/index.html.erb
<p id="notice"><%= notice %></p>

<nav>
  <div class="navbar navbar-default">
    <div class="navbar-inner">
      <div class="container">
        <a class="navbar-brand" href="#"><strong>RESCUE ME</strong></a>
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", welcome_path %></li>
            <li><a href="#">About Us</a></li>
            <li class="divider-vertical"></li>
            <li><a href="dogs#show">Adopt</a></li>
            <li class="active"><a href="info_pages#index">Information</a></li>
            <li><a href="#">Sponsor</a></li>
          </ul>
        </div>
      </div>
    </div>
</nav>


<head>

<div class="panel panel-info">
  <div class="panel-heading">
    <h2>Adoption Information Page</h2>
  </div>
</div>

</head>

<body>

<div class="col-md-4">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3>Search Options</h3>
      <h5>Click to select</h5>
      <div class="panel-body">
        <button id="alldogs-close-CSS">All Dogs</button>

        <button id="puppies-close-CSS">Puppies</button>

        <button id="youngdog-close-CSS">Young Dogs</button>

        <button id="seniordog-close-CSS">Senior Dogs</button>

        <button id="specialdogs-close-CSS">Special Needs Dogs</button>
      </div>
    </div>
  </div>
</div>

<div class="col-md-8">
  <div class="panel panel-success">
    <h3 class="panel-heading"> Information You Need to Know</h3>
        <div class="panel-body">
          <div class="well well-sm"><strong>What you need for your new family member</strong></div>
            <p> </p>

          <div class="well well-sm"><strong>Expectations</strong></div>
          <p> </p>

          <div class="well well-sm"><h4>Puppy proofing your home</h4><br>
              <p> You’ve now decided what breed is a good fit for you and your family, and perhaps you have even the found the perfect puppy already! Congrats! Bringing a puppy home requires a lot more work than just picking it up and putting it in the car, - See more at:
            <a href="http://www.dogwatch.com/dogtails/2011/06/10/puppy-proofing-and-preparation">Dog Watch</a>
          </p>
          </div>

          <div class="well well-sm"><strong>Aproximate Vetinary Costs</strong></div>
          <p> </p>

          <div class="well well-sm"><strong>Recommended Vets</strong></div>
          <p> </p>

          <div class="well well-sm"><strong>Dog Parks</strong></div>
          <p> </p>

          <div class="well well-sm"><strong>Dog Day Camps, kennels and Pet Sitters</strong></div>
          <p> </p>

        </div>
      </div>

    </div>
</div>
</body>

<footer>
<h5> DISCLAIMER: THIS IS A CLASS INSTRUCTIONAL ASSIGNMENT AND IS IN NO WAY AN ACTUAL ORGANIZATION.</h5>
</footer>

app/views/info_pages/new.html.erb
<h1>New Info Page</h1>

<%= render 'form' %>

<%= link_to 'Back', info_pages_path %>

app/views/info_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Information:</strong>
  <%= @info_page.information %>
</p>

<%= link_to 'Edit', edit_info_page_path(@info_page) %> |
<%= link_to 'Back', info_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetAdoption</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <nav>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <%= yield %>
          </div>
          <div class="mastfoot">
            <div class="inner">
            </div>
          </div>
        </div>
      </div>
    </div>

</body>
</html>

app/views/welcome/about.html.erb
<div class="navbar navbar-default">
  <div class="navbar-inner">
  <div class="container">
    <a class="navbar-brand" href="#">RESCUE ME</a>
    <ul class="nav navbar-nav">/
      <li><%= link_to "Home", welcome_path %></li>
      <li class="active"><a href="about#page">About Us</a></li>
      <li class="divider-vertical"></li>
      <li><a href="dogs#show">Adopt</a></li>
      <li><a href="info_pages#index">Information</a></li>
      <li><a href="#">Sponsor</a></li>
    </ul>
  </div>
</div>


<h1>About RESCUE ME</h1>

<p>Rescue Me Pet Adoptions is a non-profit animal rescue organization that has rescued stray or abandoned cats and dogs in the Triangle Area of North Carolina since 2015.</p><br>


<h5> DISCLAIMER: THIS IS A CLASS INSTRUCTIONAL ASSIGNMENT AND IS IN NO WAY AN ACTUAL ORGANIZATION.</h5>

app/views/welcome/index.html.erb
<div class="navbar navbar-default">
  <div class="navbar-inner">
  <div class="container">
    <a class="navbar-brand" href="#">RESCUE ME</a>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", welcome_path %></li>
      <li><a href="about#page">About Us</a></li>
      <li class="divider-vertical"></li>
      <li><a href="dogs#show">Adopt</a></li>
      <li><a href="info_pages#index">Information</a></li>
      <li><a href="#">Sponsor</a></li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="jumbotron text-center">
    <h1 style="color:#10a1ff">RESCUE ME</h1>
    <p class="lead">To secure equal treatment and opportunity for ALL dogs and to create a world in which all companion animals find compassionate, permanent homes..</p>
    <p><a class="btn btn-large btn-success" href="http://bootply.com/tagged/bootstrap-3" target="ext">APPLICATION</a></p>
  </div>

<div class="row">
    <div class="col-lg-6">
      <h4>MISSION STATEMENT</h4>
        <p><em>RESCUE ME's mission is to aid homeless, abandoned and neglected dogs, to nurture them in the foster care of volunteers, to provide veterinary care and socialization, and to place them in permanent loving and responsible homes. RESCUE ME also works to decrease the population of homeless dogs and cats through its spay/neuter programs.</em></p>

      <h4>VISION</h4>
        <p><em>RESCUE ME's mission is to aid homeless, abandoned and neglected dogs, to nurture them in the foster care of volunteers, to provide veterinary care and socialization, and to place them in permanent loving and responsible homes. RESCUE ME also works to decrease the population of homeless dogs and cats through its spay/neuter programs.</em></p>

      <h4>OUR VALUES</h4>
        <p><em>BlahBlahBlah</em></p>

    </div>


      <div class="inner-content-wrapper center">
          <a href="https://twitter.com/rabbyia"><i class="fa fa-twitter twitter"></i></a>
          <a href="https://github.com/rabbyia"><i class="fa fa-github-alt github"></i></a>
          <a href=""><i class="fa fa-linkedin linkedin"></i></a>
          <a href="mailto:me(ATs)rabbyia.shabbir(DOTs)com?Subject=Hello!"><i class="fa fa-envelope email"></i></a>
      </div>
</div>

        <footer>
            <div>
                <p>RESCUE ME &#169; 2015</p>
                <p>Handcrafted with love by TTS students</p>
                <p><em>Kelly M Curtis, Rabbyia Shabbir and Nicole Rudi</em></p>
            </div>

            <h5> DISCLAIMER: THIS IS A CLASS INSTRUCTIONAL ASSIGNMENT AND IS IN NO WAY AN ACTUAL ORGANIZATION.</h5>

        </footer>